# Generated by Django 6.0.4 on 2026-04-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.AddField(
            model_name='service',
            name='margin_percent',
            field=models.FloatField(default=30),
        ),
        migrations.AlterField(
            model_name='service',
            name='cost_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='provider_service_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
