# Generated by Django 6.0.4 on 2026-04-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_order_service_name_order_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(default='Genral', max_length=100),
        ),
    ]
