# Generated by Django 6.0.4 on 2026-04-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='max_qty',
            field=models.IntegerField(default=1000000),
        ),
        migrations.AddField(
            model_name='service',
            name='min_qty',
            field=models.IntegerField(default=1),
        ),
    ]
