# Generated by Django 6.0.4 on 2026-04-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_withdrawrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_reseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='reseller_margin',
            field=models.FloatField(default=10),
        ),
    ]
